### ISSUE TITLE
Auth & Component

### ISSUE THREAD

**Issue by Kodemon** [bentojs/app-core#2]
Found an issue when triggering the authentication re-render event that `this.auth` is not properly assigned. `this.props._auth` does work as expected though, I am now thinking it would be a good idea to throw away `this.auth` and rename `this.props._auth` to `this.props.auth` for consistency across both bento and react components.

As in when you pass props from bento to a react component its more consistent to use `this.props.auth` on bento since you can't have `this.auth` on a react component.

@mattgi whats your take on this?

**Comment by mattgi** [comment]
this.props.auth ftw :+1:
